---

defaults: &defaults
  elasticsearch: &elasticsearchdefaults
    index: "plutus"
  cassandra: &cassandradefaults
    keyspace: "plutus"
      
dev:
  <<: *defaults
  elasticsearch:
    <<: *elasticsearchdefaults
    hosts:
      - 127.0.0.1:9200
  cassandra:
    <<: *cassandradefaults
    hosts:
      - 127.0.0.1
